name: "Install catkin_lint"
description: "Installs rosdep and catkin_lint for ROS1"
inputs:
  distro:
    description: "ROS distro to check against"
    required: false
    deprecationMessage: "The 'distro' input is obsolete and will be removed in a future version."
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get -q update
        sudo apt-get -q install catkin-lint
